//Definitions

#define ROTATION_TIME 3.0f
#define ROTATION_ANGLE 3600.0f

#define BUTTON_TRANSITION_TIME 0.2f
#define TRANSITION_TIME_FAST 0.2f

#define EASING_RATE 2.0f

#define SPRITE_SECTOR_1 "hammer.png"
#define SPRITE_SECTOR_2 "gem.png"
#define SPRITE_SECTOR_3 "brush.png"
#define SPRITE_SECTOR_4 "coin.png"
#define SPRITE_SECTOR_5 "hammer.png"
#define SPRITE_SECTOR_6 "gem.png"
#define SPRITE_SECTOR_7 "brush.png"
#define SPRITE_SECTOR_8 "heart.png"

#define QTY_SECTOR_1 "x1"
#define QTY_SECTOR_2 "x75"
#define QTY_SECTOR_3 "x1"
#define QTY_SECTOR_4 "x750"
#define QTY_SECTOR_5 "x3"
#define QTY_SECTOR_6 "x35"
#define QTY_SECTOR_7 "x3"
#define QTY_SECTOR_8 "30 min"

#define P_SECTOR_1 20
#define P_SECTOR_2 5
#define P_SECTOR_3 20
#define P_SECTOR_4 5
#define P_SECTOR_5 10
#define P_SECTOR_6 10
#define P_SECTOR_7 10
#define P_SECTOR_8 20

#define SECTOR_LIMIT_1 P_SECTOR_1
#define SECTOR_LIMIT_2 P_SECTOR_1 + P_SECTOR_2
#define SECTOR_LIMIT_3 P_SECTOR_1 + P_SECTOR_2 + P_SECTOR_3
#define SECTOR_LIMIT_4 P_SECTOR_1 + P_SECTOR_2 + P_SECTOR_3 + P_SECTOR_4 + P_SECTOR_5
#define SECTOR_LIMIT_5 P_SECTOR_1 + P_SECTOR_2 + P_SECTOR_3 + P_SECTOR_4 + P_SECTOR_5 + P_SECTOR_6
#define SECTOR_LIMIT_6 P_SECTOR_1 + P_SECTOR_2 + P_SECTOR_3 + P_SECTOR_4 + P_SECTOR_5 + P_SECTOR_6 + P_SECTOR_7
#define SECTOR_LIMIT_7 P_SECTOR_1 + P_SECTOR_2 + P_SECTOR_3 + P_SECTOR_4 + P_SECTOR_5 + P_SECTOR_6 + P_SECTOR_7 + P_SECTOR_8
#define SECTOR_LIMIT_8 100

#define ANGLE_SECTOR_1 22.5f
#define ANGLE_SECTOR_2 67.5f
#define ANGLE_SECTOR_3 112.5f
#define ANGLE_SECTOR_4 157.5f
#define ANGLE_SECTOR_5 202.5f
#define ANGLE_SECTOR_6 247.5f
#define ANGLE_SECTOR_7 292.5f
#define ANGLE_SECTOR_8 337.5f

#define CIRCLE_COORDS_1 0.177f
#define CIRCLE_COORDS_2 0.366f
#define CIRCLE_COORDS_3 0.634f
#define CIRCLE_COORDS_4 0.823f

#define SPRITE_LABEL_HEIGHT 0.2f

#define SPIN_TAG 0
#define CLAIM_TAG 1